### ISSUE TITLE
Basic screens

### ISSUE THREAD

**Issue by veetaw** [C01-GlucoseGuardian/mobileApp#1]
### TODO
- [ ] Splash screen : A screen the user will see when opening the app
- [x] Landing screen: A screen the user will see the FIRST time he's visiting the app, with a brief introduction
- [x] Login screen: Will need to have three fields (??) email, password and OTP code*
- [ ] use colors from mockups in the screens

## Login ui
Login UI on mobile should be similar to the desktop one:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/13486742/213484434-cef543aa-500e-4c59-8543-175ebe455186.png">

*should be OTP code asked after successful login or are we stating that we already have the code before login? How are we going to check if it is valid? cc @HandyMenny

**Comment by veetaw** [comment]
merged #2
