### ISSUE TITLE
TODO: rush

### ISSUE THREAD

**Issue by veetaw** [C01-GlucoseGuardian/mobileApp#12]
- [x] change password
- [x] otp login
- [x] tutore
- [x] send feedback
- [x] logout
- [x] store taken meds
- [x] #14
- [x] tutore notifications 
- [x] generate random measurements every n seconds and update ui (20m-2h (depends on bloc))
- [x] receive firebase notifications (30m)
- [x] tutore send notifications (2h)

**Comment by veetaw** [comment]
tutorial on first start?

**Comment by veetaw** [comment]
sium
