### ISSUE TITLE
Paziente homepage

### ISSUE THREAD

**Issue by veetaw** [C01-GlucoseGuardian/mobileApp#4]
### Design
PazienteHome should have a greeting on the top left corner in the app bar in a format like "Ciao, $name!", then a CGM icon button that will bring the user to a screen where they can connect the cgm device.
Then there will be a day selector with the last 7 days, with the current day selected highlighted in some way, the starting position will be today.
There will be a card indicating the last measurement, with the day highest, lower and the normal value for glucose in the blood. The UOM will be mmol/L.
Then there's a graph with the glucose levels on the y axis and the time where the measurement has been made in the 24 hours span selected.
The bottom app bar will have 5 buttons: home (starting position), agenda, notifications, profile and doctor profile.

##### Sketch
![IMG_0021](https://user-images.githubusercontent.com/13486742/213702488-59654951-a634-471c-8e82-a11dfed971bf.jpg)

## Tasks
- [x] HomePage
  - [x] AppBar
  - [x] CGM Icon
  - [x] Last 7 days selector component
  - [x] Glucose measurement card component
  - [x] Find graph library
  - [x] Graph card
  - [x] BottomAppBar
  
all the implementation will be on branch feature-002

**Comment by veetaw** [comment]
Current state as of commit: 469ce771d159b1b15d4158eeee92275fd0486c4d

<img width="571" alt="image" src="https://user-images.githubusercontent.com/13486742/213730599-4e91f4a3-d88c-4454-81c0-31318e11318a.png">

**Comment by veetaw** [comment]
Update as of commit 1145ad86460300a2c67e4aa743274f0b08017983

<img width="571" alt="image" src="https://user-images.githubusercontent.com/13486742/213877100-cb060dcf-ca4d-40a9-9c84-3ef5458abc82.png">


TODO: need to find a way to group 1440 measurements per day in the chart

**Comment by veetaw** [comment]
Waiting for review #5

**Comment by veetaw** [comment]
closed by #5
